/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EverVault;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EverVaultTest {
    @Test void () {
        EverVault classUnderTest = new EverVault("test");
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
