/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EverVault;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WhenEncryptingData {
    @Test void EncryptingNumberGeneratesEvNumberType() {
        final int data = 1;

        EverVault everVault = new EverVault("test");
        everVault.Encrypt(data);
        asse

        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    void assertEverVaultStringFormat(String data) {
        var splitted = data.spl

    }
}
