/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package evervault.services;

import evervault.contracts.*;
import evervault.exceptions.*;
import evervault.models.CageRunResult;
import evervault.utils.EcdhCurve;

import java.io.IOException;
import java.security.*;
import java.security.spec.InvalidKeySpecException;
import java.time.Duration;
import java.time.Instant;

public abstract class EvervaultService {
    protected IProvideCagePublicKeyFromHttpApi cagePublicKeyFromEndpointProvider;
    protected IProvideECPublicKey ecPublicKeyProvider;
    protected IProvideSharedKey sharedKeyProvider;
    protected IProvideEncryptionForObject encryptionProvider;
    protected IProvideCageExecution cageExecutionProvider;
    protected IProvideCircuitBreaker circuitBreakerProvider;

    protected final static int NEW_KEY_TIMESTAMP = 15;
    protected final int getCageHash = "getCagePublicKeyFromEndpoint".hashCode();
    protected final int runCageHash = "runCage".hashCode();
    protected Instant currentSharedKeyTimestamp;
    protected byte[] generatedEcdhKey;
    protected byte[] sharedKey;
    protected IProvideTime timeProvider;
    protected PublicKey teamKey;

    // Virtual method
    protected String getEvervaultBaseUrl() {
        return "";
    }

    // Virtual method
    protected String getEvervaultRunUrl() {
        return "";
    }

    protected void setupCircuitBreaker(IProvideCircuitBreaker provideCircuitBreaker) {
        if (provideCircuitBreaker == null) {
            throw new NullPointerException(IProvideCircuitBreaker.class.getName());
        }

        this.circuitBreakerProvider = provideCircuitBreaker;
    }

    protected void setupCageExecutionProvider(IProvideCageExecution cageExecutionProvider) {
        if (cageExecutionProvider == null) {
            throw new NullPointerException(IProvideCageExecution.class.getName());
        }

        this.cageExecutionProvider = cageExecutionProvider;
    }

    protected void setupKeyProviders(IProvideCagePublicKeyFromHttpApi cagePublicKeyFromEndpointProvider,
                                     IProvideECPublicKey ecPublicKeyProvider,
                                     IProvideSharedKey sharedKeyProvider,
                                     IProvideTime timeProvider,
                                     EcdhCurve ecdhCurve) throws HttpFailureException, InvalidAlgorithmParameterException, IOException, NoSuchAlgorithmException, InvalidKeySpecException, InvalidKeyException, InterruptedException, NotPossibleToHandleDataTypeException, MaxRetryReachedException, NoSuchProviderException {
        if (cagePublicKeyFromEndpointProvider == null) {
            throw new NullPointerException(IProvideCagePublicKeyFromHttpApi.class.getName());
        }

        if (ecPublicKeyProvider == null) {
            throw new NullPointerException(IProvideECPublicKey.class.getName());
        }

        if (sharedKeyProvider == null) {
            throw new NullPointerException(IProvideSharedKey.class.getName());
        }

        if (timeProvider == null) {
            throw new NullPointerException(IProvideTime.class.getName());
        }

        this.timeProvider = timeProvider;
        this.cagePublicKeyFromEndpointProvider = cagePublicKeyFromEndpointProvider;
        this.ecPublicKeyProvider = ecPublicKeyProvider;
        this.sharedKeyProvider = sharedKeyProvider;

        setupKeys(ecdhCurve);
    }

    protected void setupEncryption(IProvideEncryptionForObject encryptionProvider) {
        if (encryptionProvider == null) {
            throw new NullPointerException(IProvideSharedKey.class.getName());
        }

        this.encryptionProvider = encryptionProvider;
    }

    private void setupKeys(EcdhCurve ecdhCurve) throws HttpFailureException, IOException, InterruptedException, NoSuchAlgorithmException, InvalidKeySpecException, InvalidAlgorithmParameterException, InvalidKeyException, NotPossibleToHandleDataTypeException, MaxRetryReachedException, NoSuchProviderException {
        var teamEcdhKey = circuitBreakerProvider.execute(getCageHash, () -> cagePublicKeyFromEndpointProvider.getCagePublicKeyFromEndpoint(getEvervaultBaseUrl()));
        if (ecdhCurve.equals(EcdhCurve.SECP256R1)) {
            teamKey = ecPublicKeyProvider.getEllipticCurvePublicKeyFrom(teamEcdhKey.ecdhP256Key);
        } else {
            teamKey = ecPublicKeyProvider.getEllipticCurvePublicKeyFrom(teamEcdhKey.ecdhKey);
        }

        generateSharedKey();
    }

    private void generateSharedKey() throws InvalidAlgorithmParameterException, NoSuchAlgorithmException, InvalidKeyException {
        currentSharedKeyTimestamp = timeProvider.GetNow();
        var generated = sharedKeyProvider.generateSharedKeyBasedOn(teamKey);

        this.sharedKey = generated.SharedKey;
        this.generatedEcdhKey = generated.GeneratedEcdhKey;
    }

    public Object encrypt(Object data) throws NotPossibleToHandleDataTypeException, IOException, MandatoryParameterException, InvalidCipherException, InvalidAlgorithmParameterException, NoSuchAlgorithmException, InvalidKeyException {
        if (data == null) {
            throw new MandatoryParameterException("data");
        }

        if (Duration.between(currentSharedKeyTimestamp, timeProvider.GetNow()).toMinutes() >= NEW_KEY_TIMESTAMP) {
            generateSharedKey();
        }

        return this.encryptionProvider.encrypt(data);
    }

    public CageRunResult run(String cageName, Object data, boolean async, String version) throws HttpFailureException, IOException, InterruptedException, MandatoryParameterException, NotPossibleToHandleDataTypeException, MaxRetryReachedException {
        if (cageName == null || cageName.isEmpty()) {
            throw new MandatoryParameterException("cageName");
        }

        if (data == null) {
            throw new MandatoryParameterException("data");
        }

        return circuitBreakerProvider.execute(runCageHash, () -> cageExecutionProvider.runCage(getEvervaultRunUrl(), cageName, data, async, version));
    }
}
