plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.evervault:lib:4.2.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClass = 'com.evervault.examples.OfflineEncrypt'
}

tasks.named('run', JavaExec) {
    standardInput = System.in
}
