name: sdk

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_API_KEY: ${{ secrets.ENVIRONMENT_API_KEY }}
      EV_API_HOST: api.evervault.com
      EV_CAGE_RUN_HOST: run.evervault.com
      EV_RELAY_HOST: strict.relay.evervault.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: build project
        run: ./gradlew clean build
      - name: unit tests
        run: ./gradlew test --info
      - name: Upload unit test report on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failed_unit_tests
          path: ${{ github.workspace }}/lib/build/reports/tests/test
      - name: integration tests
        env:
          ENVIRONMENT_API_KEY: ${{ secrets.ENVIRONMENT_API_KEY }}
          EV_API_URL: https://api.evervault.com
          EV_CAGE_RUN_URL: https://run.evervault.com
        run: ./gradlew integrationTests --info
      - name: Upload integration test report on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failed_integration_tests
          path: ${{ github.workspace }}/lib/build/reports/tests/integrationTests