name: sdk

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lin-build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_APIKEY: ${{ secrets.ENVIRONMENT_APIKEY }}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo bash ${GITHUB_WORKSPACE}/install_dependencies.bash
      - name: build project
        run: gradle clean build
      - name: unit tests
        run: ./gradlew test
      - name: Upload unit test report on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failed_unit_tests.html
          path: /home/runner/work/evervault-java/evervault-java/lib/build/reports/tests/integrationTests/index.html
      - name: integration tests
        run: ./gradlew integrationTests
      - name: Upload integration test report on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failed_integration_tests.html
          path: /home/runner/work/evervault-java/evervault-java/lib/build/reports/tests/integrationTests/index.html
