name: sdk

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: [8, 11, 16, 17, 21]
    env:
      ENVIRONMENT_API_KEY: ${{ secrets.ENVIRONMENT_API_KEY }}
      EV_API_HOST: api.evervault.com
      EV_CAGE_RUN_HOST: run.evervault.com
      EV_RELAY_HOST: strict.relay.evervault.com
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }} with ${{ matrix.distribution }}
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}
      - name: build project
        run: ./gradlew clean build
      - name: unit tests
        run: ./gradlew test --info
      - name: Upload unit test report on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failed_unit_tests
          path: ${{ github.workspace }}/lib/build/reports/tests/test