name: sdk

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lin-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo bash ${GITHUB_WORKSPACE}/install_dependencies.bash
      - name: build project
        run: gradle build
      - name: unit tests
        run: gradle test --tests 'EverVault.UnitTests*'
      - name: integration tests
        run: gradle test --tests 'EverVault.IntegrationTests*'